const btn = document.querySelector(".fleche");

btn.addEventListener("click", () => {

    window.scrollTo({
        top: 800,
        left: 0,
        behavior: "smooth"
    })

})

const btn_2 = document.querySelector(".fleche_2");

btn_2.addEventListener("click", () => {

    window.scrollTo({
        top: 2024,
        left: 0,
        behavior: "smooth"
    })

})

let media400 = window.matchMedia("(max-width: 400px)");

if(media400.matches)
{
    btn.addEventListener("click", () => {

        window.scrollTo({
            top: 1250,
            left: 0,
            behavior: "smooth"
        })
    
    })
    btn_2.addEventListener("click", () => {

        window.scrollTo({
            top: 1924,
            left: 0,
            behavior: "smooth"
        })
    
    })
}

const txtAnim = document.querySelector("h1");

new Typewriter(txtAnim, 
{
    deleteSpeed: 10
})
.changeDelay(10)
.typeString("$")
.pauseFor(30)
.deleteChars(1)
.typeString("_")
.pauseFor(30)
.deleteChars(1)
.typeString("M")
.pauseFor(70)
.typeString("^")
.pauseFor(30)
.deleteChars(1)
.typeString("%")
.pauseFor(30)
.deleteChars(1)
.typeString("o")
.pauseFor(70)
.typeString("@")
.pauseFor(30)
.deleteChars(1)
.typeString("#")
.pauseFor(30)
.deleteChars(1)
.typeString("i")
.pauseFor(70)
.typeString(")")
.pauseFor(30)
.deleteChars(1)
.typeString("<")
.pauseFor(30)
.deleteChars(1)
.typeString(" ")
.pauseFor(70)
.typeString("{")
.pauseFor(30)
.deleteChars(1)
.typeString("è")
.pauseFor(30)
.deleteChars(1)
.typeString("c")
.pauseFor(70)
.typeString("ç")
.pauseFor(30)
.deleteChars(1)
.typeString("~")
.pauseFor(30)
.deleteChars(1)
.typeString("'")
.pauseFor(70)
.typeString("@")
.pauseFor(30)
.deleteChars(1)
.typeString("#")
.pauseFor(30)
.deleteChars(1)
.typeString("e")
.pauseFor(70)
.typeString("µ")
.pauseFor(30)
.deleteChars(1)
.typeString("¤")
.pauseFor(30)
.deleteChars(1)
.typeString("s")
.pauseFor(70)
.typeString("]")
.pauseFor(30)
.deleteChars(1)
.typeString("+")
.pauseFor(30)
.deleteChars(1)
.typeString("t")
.pauseFor(70)
.typeString("§")
.pauseFor(30)
.deleteChars(1)
.typeString("-")
.pauseFor(30)
.deleteChars(1)
.typeString(" ")
.pauseFor(70)
.typeString("°")
.pauseFor(30)
.deleteChars(1)
.typeString("|")
.pauseFor(30)
.deleteChars(1)
.typeString("P")
.pauseFor(70)
.typeString("?")
.pauseFor(30)
.deleteChars(1)
.typeString("¨")
.pauseFor(30)
.deleteChars(1)
.typeString("o")
.pauseFor(70)
.typeString("!")
.pauseFor(30)
.deleteChars(1)
.typeString(">")
.pauseFor(30)
.deleteChars(1)
.typeString("z")
.pauseFor(70)
.typeString("2")
.pauseFor(30)
.deleteChars(1)
.typeString("=")
.pauseFor(30)
.deleteChars(1)
.typeString("a")
.pauseFor(70)
.typeString("£")
.pauseFor(30)
.deleteChars(1)
.typeString(";")
.pauseFor(30)
.deleteChars(1)
.typeString("y")
.pauseFor(500)
.typeString("é")
.pauseFor(30)
.deleteChars(1)
.typeString("²")
.pauseFor(30)
.deleteChars(1)
.typeString(",")
.pauseFor(70)
.typeString("`")
.pauseFor(30)
.deleteChars(1)
.typeString("(")
.pauseFor(30)
.deleteChars(1)
.typeString(" ")
.pauseFor(70)
.typeString("0")
.pauseFor(30)
.deleteChars(1)
.typeString("§")
.pauseFor(30)
.deleteChars(1)
.typeString("j")
.pauseFor(70)
.typeString("]")
.pauseFor(30)
.deleteChars(1)
.typeString("s")
.pauseFor(30)
.deleteChars(1)
.typeString("e")
.pauseFor(70)
.typeString("8")
.pauseFor(30)
.deleteChars(1)
.typeString("e")
.pauseFor(30)
.deleteChars(1)
.typeString(" ")
.pauseFor(70)
.typeString("y")
.pauseFor(30)
.deleteChars(1)
.typeString("@")
.pauseFor(30)
.deleteChars(1)
.typeString("D")
.pauseFor(70)
.typeString("a")
.pauseFor(30)
.deleteChars(1)
.typeString("<")
.pauseFor(30)
.deleteChars(1)
.typeString("e")
.pauseFor(70)
.typeString("/")
.pauseFor(30)
.deleteChars(1)
.typeString("*")
.pauseFor(30)
.deleteChars(1)
.typeString("v")
.pauseFor(70)
.typeString("$")
.pauseFor(30)
.deleteChars(1)
.typeString("!")
.pauseFor(30)
.deleteChars(1)
.typeString(" ")
.pauseFor(70)
.typeString("?")
.pauseFor(30)
.deleteChars(1)
.typeString("è")
.pauseFor(30)
.deleteChars(1)
.typeString("e")
.pauseFor(70)
.typeString("&")
.pauseFor(30)
.deleteChars(1)
.typeString("¤")
.pauseFor(30)
.deleteChars(1)
.typeString("n")
.pauseFor(70)
.typeString("^")
.pauseFor(30)
.deleteChars(1)
.typeString("#")
.pauseFor(30)
.deleteChars(1)
.typeString(' ')
.pauseFor(70)
.typeString("^")
.pauseFor(30)
.deleteChars(1)
.typeString("#")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffc400">H</span>')
.pauseFor(70)
.typeString("(")
.pauseFor(30)
.deleteChars(1)
.typeString("_")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffc400">T</span>')
.pauseFor(70)
.typeString("$")
.pauseFor(30)
.deleteChars(1)
.typeString("µ")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffc400">M</span>')
.pauseFor(70)
.typeString("7")
.pauseFor(30)
.deleteChars(1)
.typeString("§")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffc400">L</span>')
.pauseFor(600)
.deleteChars(4)
.typeString("+")
.pauseFor(30)
.deleteChars(1)
.typeString("]")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #00ffff">C</span>')
.pauseFor(70)
.typeString("é")
.pauseFor(30)
.deleteChars(1)
.typeString("{")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #00ffff">S</span>')
.pauseFor(70)
.typeString("²")
.pauseFor(30)
.deleteChars(1)
.typeString(";")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #00ffff">S</span>')
.pauseFor(600)
.deleteChars(3)
.typeString("à")
.pauseFor(30)
.deleteChars(1)
.typeString("#")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #b700ff">J</span>')
.pauseFor(70)
.typeString("@")
.pauseFor(30)
.deleteChars(1)
.typeString("ç")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #b700ff">S</span>')
.pauseFor(600)
.deleteChars(2)
.typeString("%")
.pauseFor(30)
.deleteChars(1)
.typeString("_")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffff00">P</span>')
.pauseFor(70)
.typeString("0")
.pauseFor(30)
.deleteChars(1)
.typeString("&")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffff00">y</span>')
.pauseFor(70)
.typeString("à")
.pauseFor(30)
.deleteChars(1)
.typeString("-")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffff00">t</span>')
.pauseFor(70)
.typeString("^")
.pauseFor(30)
.deleteChars(1)
.typeString("#")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffff00">h</span>')
.pauseFor(70)
.typeString("x")
.pauseFor(30)
.deleteChars(1)
.typeString("£")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffff00">o</span>')
.pauseFor(70)
.typeString("?")
.pauseFor(30)
.deleteChars(1)
.typeString("°")
.pauseFor(30)
.deleteChars(1)
.typeString('<span style="color: #ffff00">n</span>')
.pauseFor(70)
.typeString("|")
.pauseFor(30)
.deleteChars(1)
.typeString("¤")
.pauseFor(30)
.deleteChars(1)
.typeString(' ')
.pauseFor(70)
.typeString(";")
.pauseFor(30)
.deleteChars(1)
.typeString("$")
.pauseFor(30)
.deleteChars(1)
.typeString('!')
.pauseFor(70)
.start()

setTimeout(start, 4400);
function start() 
{
    document.querySelector('.titre').style.animation='github 1s linear infinite'
    setTimeout(okok, 900)
}
function okok()
{
    document.querySelector('.titre').style.animation='none';
}


// .typeString('<span style="color: #27ae60">CSS</span>')
















